### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by nadbal07** [JDavidMartin/FifaTrader#1]
Hello. Can you help me how to setting up and run the whole program?
I have VS 2017. :)
Thank you. :)

**Comment by JDavidMartin** [comment]
Hiya mate,
So i've got an action to write up some documentation for this.
I'll try and get it done for you ASAP.
I'll let you know when it's done

**Comment by nadbal07** [comment]
Thank you JDavidMartin. :)
Good luck with it.

**Comment by JDavidMartin** [comment]
I've updated the ReadMe, let me know if this answers your questions.
Let me know if any part is unclear, I'd be happy to help

**Comment by nadbal07** [comment]
Thank you! I going to try it now. :)

**Comment by nadbal07** [comment]
Hi, its me again.
https://prnt.sc/rlfata
Its my problem. Can you help me how Can i fix it? :)

I just run the solution and build the program.

**Comment by JDavidMartin** [comment]
Following from this thread https://github.com/dotnet/aspnetcore/issues/15656
Could you make sure you're running .Net core 3.1?

**Comment by nadbal07** [comment]
Downloaded and installed these things:
https://prnt.sc/rlfv30

Now I open the solution, build and the error is:
https://prnt.sc/rlfvqs

How I can fix it? I already installed that I show you before.
Please help me. :)

**Comment by JDavidMartin** [comment]
Hey
Could you check out these steps please?
https://www.ryadel.com/en/current-net-sdk-not-support-net-core-3-0-fix/
I'll try and replicate this issue. But it seems like a .net installation issue.
Let me know how you get on.

**Comment by nadbal07** [comment]
https://prnt.sc/rlg3lz
Sadly I don't have these options in my Visual Studio 2017.
Maybe that is the problem I have VS 2017.
I checked and I have that sdk.
https://prnt.sc/rlg40j

**Comment by JDavidMartin** [comment]
Ok, please try VS 2019, Community version is free
https://visualstudio.microsoft.com/vs/

**Comment by nadbal07** [comment]
Ok, I'll try it yesterday, because I need to go somewhere. :)
Thank you for your help, I'll come back to you tomorrow! 👍

**Comment by nadbal07** [comment]
Working with visual studio 2019 :)
Now i'm in validate token, if i need any help I'll back to you! :)

**Comment by JDavidMartin** [comment]
Glad to hear it. I'm going to close this issue now.
If you run into any more problems, or have general feedback about the app, do please let me know.
